// <auto-generated />
namespace NetCommunity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2keys));
        
        string IMigrationMetadata.Id
        {
            get { return "201410201127429_2keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
